### ISSUE TITLE
For-loop with range cannot handle more than one argument

### ISSUE THREAD

**Issue by ghost** [Intuity/prologue#10]
Python's `range` function can take multiple arguments - when more than one argument is used within a `#for` loop directive, Prologue seems to have a problem:

```
#for i in range(0, 16):
Number is $(i)
#endfor
```

Raises an exception:

```
Caught TypeError when evaluating ...; 'tuple' cannot be interpreted as an integer
```

**Comment by Intuity** [comment]
This issue has been fixed
