### ISSUE TITLE
Allow directives to be queried and de-registered

### ISSUE THREAD

**Issue by blu-peter** [Intuity/prologue#4]
There is no mechanism to check what directives are currently registered, nor any way to remove an already registered directive. It should also be an option to not register the prime directives when creating a Prologue instance.

**Comment by Intuity** [comment]
There is a new `register_prime` switch to Prologue which disables the default registration, and the following methods have been added:
 
 * `deregister_directive` - allows a directive to be removed once registered
 * `list_directives` - returns a unique list of all of the registered directives (no matter how many tags refer to one directive)
 * `has_directive` - allows a tag to be tested to see if it is already used
